### ISSUE TITLE
Go release missing several commits

### ISSUE THREAD

**Issue by jadekler** [googleapis/releasetool#136]
#### Environment details

  - OS: osx
  - Python version: 3.6.5
  - `releasetool` version: 2018.11.7.2

#### Problem

1. `releasetool start --language go`

Should generate a CHANGES.md with:

```
$ git log v0.33.1..HEAD --format=format:%H
f5990a4292826db021c86aa413b5149cc714a78f
3b9ae547b3d80df7227c0e71bc60c86aee8c4b89
48f90e82b521609d016f2b99269f38fc9489bcc3
022eb1645b78acb655755a0c1e185c68cd5c8eb3
56d3f5bc07d0a73b6643844c715d22ff2d097797
90772c0662468af35837da2bb1759d8ec897c69c
41590e5e6d7a5a30921e686fbc57c45545d8bf29
20d48165e15edb94128d2907ed8c9c8b2ae0a360
2a912322007f3a7f0b4e7e96ba0dfd8c4f347d33
977bdf6a60d16cd466ccbfe6c20bfc20ddf923ba
```

However, it gets generated with:

```
12-04-2018 16:21 PST

- functions: don't use a wrapper and make Resource a value
- functions/metadata: use JSON and pointers
- internal: run vet
```

aka:

```
f5990a4292826db021c86aa413b5149cc714a78f
3b9ae547b3d80df7227c0e71bc60c86aee8c4b89
48f90e82b521609d016f2b99269f38fc9489bcc3
```

**Comment by enocom** [comment]
If I recall correctly, releasetool assumes any tag that starts with `v` is a version tag, when in fact a person might have `very-bad-tag` or any other tag that starts with a `v`. When I saw a similar problem, I deleted the tag with the `v` and releasetool did the right thing.

See [here](https://github.com/googleapis/releasetool/blob/6ce51e71a700a21a2e8fcae654dc0a87159757af/releasetool/commands/start/go.py#L92-L95).

I suspect when listing tags release tool should look for `v[0-9]+` as a prefix instead.
