### ISSUE TITLE
Trouble finding the last release

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/releasetool#141]
I'm trying to run `releasetool start` against this repository:
https://github.com/googleapis/nodejs-datastore-session

I get this output, and it tries to release a `0.1.0`:
```
nodejs-datastore-session (master) $ releasetool start
o/ Hey, beckwith, let's release some stuff!
> Determining GitHub context.
Origin: JustinBeckwith/nodejs-datastore-session, Upstream: googleapis/nodejs-datastore-session
> Comparing upstream/master to master.
master is up to date with upstream/master
> Figuring out the package name.
Looks like we're releasing @google-cloud/connect-datastore.
> Figuring out what the last release was.
I couldn't figure out the last release for @google-cloud/connect-datastore, so I'm assuming this is the first release. Can you tell me which git rev/sha to start the changelog at?
Committish: 944ff59ca21f0e8a35f953cc929c4e0f0ddff659
The last release was 0.0.0.
> Gathering changes since 0.0.0
Cool, 37 changes found.
```

The problem here, is that there *was* a previous release.  The release exists here:
https://github.com/googleapis/nodejs-datastore-session/releases/tag/1.0.0

The `1.0.0` version exists on npm too:
https://www.npmjs.com/package/@google-cloud/connect-datastore

Releasetool doesn't let me override the version, so it kinda forces me to do a `0.1.0`, which obvs doesn't work.

**Comment by busunkim96** [comment]
This is because the nodejs start command expects the version tags to start with 'v'.

https://github.com/googleapis/releasetool/blob/783de94205933a7f9add2ffdddf0b0033d7106e3/releasetool/commands/start/nodejs.py#L57-L60

**Comment by busunkim96** [comment]
I think it would be fastest to rename the tag from `1.0.0` to `v1.0.0`. If that's not possible, we can modify releasetool to allow the version name to be overridden.
