### ISSUE TITLE
Publish reporter did not report status to release PR

### ISSUE THREAD

**Issue by busunkim96** [googleapis/releasetool#144]
The release job for cloud-debug-nodejs succeeded but did not report its status to the PR. 

See https://github.com/googleapis/cloud-debug-nodejs/pull/609

**Comment by theacodes** [comment]
Sponge log for the publish job is at sponge/cf625e72-6618-4d25-8d02-5d96f5960c38

**Comment by theacodes** [comment]
Relevant line:

> No github token or PR specified to report status to, returning.

Which means it either couldn't find the github token or didn't know the PR.

**Comment by theacodes** [comment]
The PR was provided to the build:

```
env_vars {
  key: "AUTORELEASE_PR"
  value: "https://github.com/googleapis/cloud-debug-nodejs/pull/609"
}
```

**Comment by theacodes** [comment]
Yep, so it's missing the GitHub token. @kinwa91 fixed this with https://github.com/googleapis/synthtool/pull/172 but it's yet to roll out. I'm going to close this, but I think we're in the clear here.
