### ISSUE TITLE
syntax error with freshly installed releasetool

### ISSUE THREAD

**Issue by ofrobots** [googleapis/releasetool#146]
After addressing #145, trying to use `releasetool`, I get the following error:

```
$ releasetool start
Traceback (most recent call last):
  File "/home/ofrobots/.local/bin/releasetool", line 7, in <module>
    from releasetool.main import main
  File "/home/ofrobots/.local/lib/python3.5/site-packages/releasetool/main.py", line 82
    prompt=f"Which language ({', '.join(_language_choices)})?",
                                                             ^
SyntaxError: invalid syntax

```

This would be a duplicate of #68, but given that is closed and I still ran into the issue means that the issue has not really been addressed. My understanding is that I need python 3.6, and the README should make this (or other disposition) clearer.

**Comment by JustinBeckwith** [comment]
cc @theacodes

**Comment by busunkim96** [comment]
I re-wrote the installation steps to make it more clear that Python >=3.6 and pip are needed. I am closing this now, but please let us know if you have any other issues running releasetool @ofrobots.
