### ISSUE TITLE
releasetool won't allow a person to specify a version manually

### ISSUE THREAD

**Issue by enocom** [googleapis/releasetool#153]
#### Environment details

  - OS: macOS 10.13.6
  - Python version: 
```
$ python --version
Python 2.7.10
$ python3 --version
Python 3.7.0
```
  - pip version:
```
$ pip --version
pip 10.0.1 from /Users/enocom/Library/Python/2.7/lib/python/site-packages/pip (python 2.7)
$ pip3 --version
pip 18.1 from /Users/enocom/homebrew/lib/python3.7/site-packages/pip (python 3.7)
```
  - `releasetool` version:
```
$ releasetool --version
2018.12.10
```

#### Steps to reproduce

```
$ cd ~
$ git clone https://code.googlesource.com/gocloud
$ cd ~/gocloud
$ git tag -ln
# ... omitted for brevity
v0.34.0         all: release v0.34.0
$ releasetool start --language go
o/ Hey, enocom, let's release some stuff!
> Figuring out the module name.
Looks like we're releasing cloud.google.com/go (relative path ).
> Figuring out what the last release was.
I couldn't figure out the last release for cloud.google.com/go, 
so I'm assuming this is the first release. 
Can you tell me which git rev/sha to start the changelog at? 0ebda48a7f143b1cce9eb37a8c1106ac762a3430
> Creating branch release-cloud.google.com/go-0.1.0
Switched to a new branch 'release-cloud.google.com/go-0.1.0'
```

Note 0ebda48a7f143b1cce9eb37a8c1106ac762a3430 is the commitish of the last release: v0.34.0.

There are two problems above:

1. releasetool fails to see the v0.34.0 tagged commit (which is the last release) and therefore erroneously assumes this is the first release.
2. releasetool never gives a person the chance to identify the correct version and instead goes along with the wrong assumption from step 1 above.

/cc @jadekler

**Comment by theacodes** [comment]
These are definitely both bugs. Releasetool should always let you manually specify the version, even if it does properly detect the last one.

@busunkim96, can you investigate?

**Comment by busunkim96** [comment]
I'm not familiar with how Go modules are organized, so I have a question. :)

Releasetool thinks a relative module is being released because of the `go.mod` in the top level directory. Is this correct? 

https://github.com/googleapis/releasetool/blob/af9a6070dbdbb85739f26880b8aa1f33e88aebc4/releasetool/commands/start/go.py#L51-L72

**Comment by enocom** [comment]
Presently, the Go Cloud libraries have a `go.mod` at the top level which includes all API libraries. In the future, there will likely be a `go.mod` within each subdirectory, e.g., one for storage, one for bigquery, one for speech, etc.

When I ran releasetool, I was hoping to do a release against the top level `go.mod`.

Thanks for looking into this! 😄
