### ISSUE TITLE
Ruby: Set release Pull Request attributes

### ISSUE THREAD

**Issue by blowmage** [googleapis/releasetool#165]
When a new Ruby Pull Request is created can the following attributes be set?

* reviewers: yoshi-ruby
* assignees: user-who-ran-releasetool

**Comment by busunkim96** [comment]
@TheRoyalTnetennba Is this no longer relevant given that Ruby uses Release-Please?

**Comment by TheRoyalTnetennba** [comment]
We're in the process of switching over.
