### ISSUE TITLE
Ruby: Incorrect version bump

### ISSUE THREAD

**Issue by busunkim96** [googleapis/releasetool#182]
The package `google-cloud` on Ruby was at version 0.58.0. A minor version bump was selected during `releasetool start`. Releasetool incorrectly made the new release 0.2.0.  

See https://github.com/googleapis/google-cloud-ruby/pull/3273 for more details.

**Comment by quartzmo** [comment]
Thanks for opening this issue for me @busunkim96. I will try to reproduce locally tomorrow and provide more detail if possible.

**Comment by quartzmo** [comment]
I should have a PR to fix this by tomorrow.
