### ISSUE TITLE
Magic proxy is currently failing, resulting in labels not being removed post publication

### ISSUE THREAD

**Issue by bcoe** [googleapis/releasetool#255]
#### Steps to reproduce

  1. Merge a release PR, resulting in autorelease tagging a release.
  2. It will enqueue a job which kicks off publication on kokoro.
  3. When this job finishes, publication will succeed, but labels will not be released; the following error will be in logs:

```bash
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://magic-github-proxy.endpoints.devrel-prod.cloud.goog/repos/googleapis/java-document-ai/issues/133/comments?
```

**Comment by SurferJeffAtGoogle** [comment]
@bcoe , what's the current status of this bug?

**Comment by bcoe** [comment]
@SurferJeffAtGoogle this problem has been addressed by introducing JWT tokens:

https://github.com/googleapis/releasetool/pull/262

python, Java, and Node.js are fixed, we're providing direction to Dotnet and Ruby.
