### ISSUE TITLE
releasetool should scan repos under GoogleCloudPlatform/ as well.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/releasetool#287]
Presently, it scans only googleapis:
https://github.com/googleapis/releasetool/blob/c1729b7198afe189fde11e2ec54373c895bfafff/autorelease/tag.py#L80

CC @jskeet

**Comment by bcoe** [comment]
seems like a great feature to make configurable, if it would help cloud events?

**Comment by jskeet** [comment]
Ping for this again? Every time I do a .NET Functions Framework release, it takes much longer than it would with releasetool sorting out the tags.

**Comment by jskeet** [comment]
Reopening as I don't believe this is actually fixed - I don't think I've seen it succeed with a GoogleCloudPlatform release, anyway.
Having just released the Functions Framework version 1.0.0, I'm unlikely to need a new release _imminently_, but it might be worth looking into.

**Comment by chingor13** [comment]
It's running against GoogleCloudPlatform, does the repository grant access to the `yoshi-automation` user?
