### ISSUE TITLE
Tagging seem to be failing consistently recently

### ISSUE THREAD

**Issue by sofisl** [googleapis/releasetool#336]
<img width="1129" alt="Screen Shot 2021-06-04 at 4 31 48 PM" src="https://user-images.githubusercontent.com/55454395/120864792-6a84a480-c552-11eb-907f-0a659b14fe90.png">

**Comment by chingor13** [comment]
Many of these are permissions issues on repositories where `yoshi-automation` user does not have access to update labels. One option could be to use the `release-please` GitHub app's credentials if we detect a `.github/release-please.yml` configuration.
