### ISSUE TITLE
'trigger' kokoro job is failing

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/releasetool#343]
![image](https://user-images.githubusercontent.com/11778530/123866088-8412d500-d8e1-11eb-839a-7afa8c512ec7.png)

**Comment by SurferJeffAtGoogle** [comment]
Still seeing it:
![image](https://user-images.githubusercontent.com/11778530/124028866-56915e80-d9a9-11eb-8e94-632497836c21.png)

**Comment by chingor13** [comment]
Have a design proposal to eliminate these permission errors. Downgrading this as it's not show stopping
