### ISSUE TITLE
A tag job is failing for nodejs-retail

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/releasetool#348]
The log:

```
Working set:
 * chore: release 1.1.5: https://github.com/googleapis/nodejs-retail/pull/70
Processing chore: release 1.1.5: https://github.com/googleapis/nodejs-retail/pull/70
> Determining what the release tag should be.
Release tag is v1.1.5.
> Determining the package version.
package version: v1.1.5.
> Grabbing the release notes.
> Creating the release.
HTTPError('422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/googleapis/nodejs-retail/releases')
cleanup
```

**Comment by chingor13** [comment]
release-please opened duplicate release PRs
See https://github.com/googleapis/release-please/issues/826

**Comment by chingor13** [comment]
1. https://github.com/googleapis/nodejs-retail/pull/70 was opened at 2:48pm, merged at 3:36pm.
2. https://github.com/googleapis/nodejs-retail/pull/71 was opened at 3:36 triggered by the push to master from PR 70 being merged

**Comment by busunkim96** [comment]
It looks like this has been resolved in release-please googleapis/release-please#826. Closing.
