### ISSUE TITLE
Trigger job failure with "ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))"

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/releasetool#368]
prod:cloud-devrel/client-libraries/autorelease/trigger build #9277

I could only find the following suspicious message:
```
ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
```
Likely an intermittent failure.

**Comment by parthea** [comment]
I'm going to close this due to inactivity. Please feel free to re-open it.
