### ISSUE TITLE
Tagging is failing due to Kokoro config change

### ISSUE THREAD

**Issue by jskeet** [googleapis/releasetool#369]
The `backend_type` option for `keystoreResource` in Kokoro configs has been removed. It's used in all three cfg files in `.kokoro-autorelease`. 

It's not clear to me whether these are still required (there are TODO comments to remove some of them) but while `backend_type` is present, we're not going to be able to release anything automatically.

(Assigning this to Bu Sun as the comments are hers - I'm hoping she'll know whether we can just remove them.)

**Comment by bcoe** [comment]
Last release worked with `FASTCONFIGPUSH` removed.
