### ISSUE TITLE
Tag jobs are failing with a permission error.

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/releasetool#380]
An example build id: 5bdf0cec-e6d8-4bfa-949b-29c9475974ad

The error message:

```
HTTPError('403 Client Error: Forbidden for url: https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-python-connector/issues/211/labels')
```

**Comment by SurferJeffAtGoogle** [comment]
I also see tag jobs failing in fusion.

**Comment by bcoe** [comment]
same thing happening here:


```
HTTPError('403 Client Error: Forbidden for url: https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-python-connector/issues/248/labels')
cleanup
```

**Comment by tmatsuo** [comment]
We can remove the `autorelease: pending` label from this PR:
https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/pull/248

**Comment by parthea** [comment]
Closing as obsolete but please feel free to re-open it.
