### ISSUE TITLE
Tag jobs are failing with 'unprocessable entity'

### ISSUE THREAD

**Issue by sofisl** [googleapis/releasetool#384]
```
Processing chore(master): release 0.39.1: https://github.com/googleapis/gapic-generator-python/pull/1133
HTTPError('422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/googleapis/gapic-generator-python/releases')
```

Example Build: e6aa45e7-6308-4da1-9dc0-70d8b3d14989

**Comment by busunkim96** [comment]
It looks like @chingor13 removed the `autorelease:...` labels from that PR. gapic-generator-python is now using release-please for tagging, so this should not be an issue in the future.
