### ISSUE TITLE
Tag job failing for dotnet-spanner-nhibernate

### ISSUE THREAD

**Issue by amanda-tarafa** [googleapis/releasetool#390]
Failure here: https://fusion2.corp.google.com/invocations/b34e2559-f5dc-4af8-a397-159dd8491903/targets/cloud-devrel%2Fclient-libraries%2Fautorelease%2Ftag;config=default/log

Only thing that seems out of the ordinary is that this repo has had no releases before.

**Comment by amanda-tarafa** [comment]
FYI: @olavloite

**Comment by olavloite** [comment]
@bcoe Friendly ping. Any update on this?

**Comment by busunkim96** [comment]
Is using release-please an option? I think that is the much better supported tool at this point in time.

https://github.com/googleapis/repo-automation-bots/tree/main/packages/release-please
https://github.com/googleapis/release-please

**Comment by amanda-tarafa** [comment]
@busunkim96 Jeff and Jon are working on a plan to move all .NET repos to release-please, but for the time being we are still using autorelease.

Once we have moved, we'll move the Spanner ORM repos as well.

**Comment by parthea** [comment]
I'm going to mark this as P2 as there is a workaround to use release-please

**Comment by amanda-tarafa** [comment]
That's not a workaround, that's a whole project on its own that we are looking into with @chingor13 . For us to use release-please there's work to be done on both the .NET repos and release please.

We were able to release mmanually last time but it'd be great if we could use our normal release process on dotnet-spanner-nhibernate the same way we do for the rest of the .NET repos.

**Comment by parthea** [comment]
@bcoe @chingor13 Do you expect that it would be quicker to fix this issue or migrate to release-please?

**Comment by bcoe** [comment]
Added to agenda for next week, sorry for missing this ping.

**Comment by amanda-tarafa** [comment]
@bcoe possibly sync-up with @jskeet as well as he'll have a better idea of the work on the .NET side of thing than I have.

**Comment by SurferJeffAtGoogle** [comment]
This issue will fall OoSLO in 27 days.

**Comment by amanda-tarafa** [comment]
Not sure why this was assigned back to me. Assigning back to @SurferJeffAtGoogle for triage.
- The .NET repos are still using `autorelease` and I'm not sure how the work to migrate them to `release-please` is going. Possibly @chingor13 may know more.
- I think this might still be an issues in the `dotnet-spanner-nhibernate` repo but @olavloite can confirm that.

**Comment by chingor13** [comment]
Still planning on migrating workloads off of releasetool onto release-please, it's just not the highest priority

**Comment by chingor13** [comment]
Only gax and google-cloud-dotnet remain on autorelease.
