### ISSUE TITLE
autorelease is failing

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/releasetool#395]
![image](https://user-images.githubusercontent.com/11778530/162272370-4f46bca5-60e3-4edc-9ec6-46fa5163e817.png)

HTTPError('403 Client Error: Forbidden for url: [https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-go-connector/issues/167/labels](https://www.google.com/url?q=https://api.github.com/repos/GoogleCloudPlatform/cloud-sql-go-connector/issues/167/labels&sa=D)')

**Comment by AlanGasperini** [comment]
Please triage

**Comment by bcoe** [comment]
All is green now.
