### ISSUE TITLE
Releasetool tag reports CI publish was successful when in fact it failed

### ISSUE THREAD

**Issue by kinwa91** [googleapis/releasetool#46]

**Comment by busunkim96** [comment]
@kinwa91 Could I have more context?

**Comment by kinwa91** [comment]
Looking at the releasetool code, it appears it's only polling for a single build(job) on CircleCI for the publish status.

I couldn't find an API for Workflows on Circle so I guess we'll need to:
 - get all builds that corresponds to the release tag
 - keep polling for the statuses for all matched builds

**Comment by theacodes** [comment]
Let's table this as Bu Sun and I are close to a solution for releasing via
kokoro.
