### ISSUE TITLE
TypeError: load_pem_private_key() missing 1 required positional argument: 'unsafe_skip_rsa_key_validation'

### ISSUE THREAD

**Issue by suztomo** [googleapis/releasetool#491]
- Search the issues already opened: https://github.com/googleapis/releasetool/issues :heavy_check_mark: 

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Linux
  - Python version: Python 3.9.13
  - pip version:
  - `releasetool` version:

#### Steps to reproduce

  1. Release googleapis/java-shared-dependencies repository (https://github.com/googleapis/java-shared-dependencies/pull/985)
  2. Check Kokoro log http://fusion2/d6fa5303-4f9b-408e-8b57-c5b055b9f98d
  3. It succeeded but the release pull request didn't get updated.

The job succeeds but it shows stacktrace of the error below.

```
[INFO] Released
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Google Cloud Shared Dependencies 2.10.3:
[INFO] 
[INFO] Google Cloud First-party Shared Dependencies ....... SUCCESS [  0.266 s]
[INFO] Google Cloud Third-party Shared Dependencies ....... SUCCESS [  0.003 s]
[INFO] Google Cloud Shared Dependencies ................... SUCCESS [  5.507 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.971 s
[INFO] Finished at: 2023-01-26T15:39:20Z
[INFO] ------------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/releasetool/__main__.py", line 213, in <module>
    main()
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/releasetool/__main__.py", line 193, in publish_reporter_finish
    releasetool.commands.publish_reporter.finish(github_token, pr, status, details)
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/releasetool/commands/publish_reporter.py", line 131, in finish
    github_token = releasetool.github.GitHubToken.token_from_dict(
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/releasetool/github.py", line 83, in token_from_dict
    access_token = get_installation_access_token(
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/releasetool/github.py", line 106, in get_installation_access_token
    private_key = default_backend().load_pem_private_key(private_key_bytes, None)
TypeError: load_pem_private_key() missing 1 required positional argument: 'unsafe_skip_rsa_key_validation'
Release status reported.
cleanup
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by lqiu96** [comment]
Hmm, this is interesting. Seems like the `unsafe_skip_rsa_key_validation` in the python cryptography module was introduced in v39.0.0 (Noted here: https://cryptography.io/en/latest/changelog/#v39-0-0). 

Synthtool has cryptography v38.0.3 pinned here: https://github.com/googleapis/synthtool/blob/71a4369253ed12bd4138f8fc68dc8d54b52fe736/synthtool/gcp/templates/java_library/.kokoro/requirements.txt#L100

and shared-dependencies has v38.0.3 in the requirements file: https://github.com/googleapis/java-shared-dependencies/blob/a1676085b41930ebf27db7d77f524f3f83a68002/.kokoro/requirements.txt#L100

**Comment by lqiu96** [comment]
@suztomo Ah, I believe the issue is that the `v2.10.3` branch of isn't using the pinned versions of python modules from synthtool. 

https://github.com/googleapis/java-shared-dependencies/blob/9a22493924f6983bd229b6218f850f7b929615a8/.kokoro/release/stage.sh#L19-L20

where it should be

https://github.com/googleapis/java-shared-dependencies/blob/a1676085b41930ebf27db7d77f524f3f83a68002/.kokoro/release/stage.sh#L19-L21

Another issue from this is that synthtool isn't being sent out to all our branches -- it only goes out to main and we would need to manually backport synthtool changes to other branches

**Comment by suztomo** [comment]
Thank you for troubleshooting. Reproducible build is difficult. 

Fortunately the newer branch has the pinned versions https://github.com/googleapis/java-shared-dependencies/blob/3.0.x/.kokoro/release/stage.sh#L19.

I'll close this issue for now as it's not blocking release and this is not releasetool's bug.
