### ISSUE TITLE
Java: gradle generated pom.xml files in build folder should be ignored

### ISSUE THREAD

**Issue by chingor13** [googleapis/releasetool#81]
Context: gax-java

After running some gradle commands, you may have a pom.xml file in the build directory. This directory is in the gitignore file and git add will fail saying that the file is ignored. releasetool then stops execution.

**Comment by chingor13** [comment]
Workaround, clean the workspace first by running `git clean -fdx` first or `./gradlew clean` before running releasetool.

**Comment by busunkim96** [comment]
@chingor13 Is this still relevant?

**Comment by chingor13** [comment]
It still happens but the workaround is ok for now.

**Comment by chingor13** [comment]
release-please handles opening Java release PRs.
