### ISSUE TITLE
Exception when origin doesn't end in .git

### ISSUE THREAD

**Issue by kjin** [googleapis/releasetool#90]
I think this is the underlying issue in #52 -- I encountered this as well. Once I added `.git` to my origin URL things were fine.

```
kelvinjin@spicydays:gcp-metadata$ releasetool start
o/ Hey, kelvinjin, let's release some stuff!
> Determining GitHub context.
Traceback (most recent call last):
  File "/usr/local/bin/releasetool", line 11, in <module>
    sys.exit(main())
  [...]
  File "/usr/local/lib/python3.7/site-packages/releasetool/commands/common.py", line 42, in _determine_origin
    origin = remotes["origin"]
KeyError: 'origin'
kelvinjin@spicydays:gcp-metadata$ git remote -v
kjin    git@github.com:kjin/gcp-metadata.git (fetch)
kjin    git@github.com:kjin/gcp-metadata.git (push)
origin  git@github.com:googleapis/gcp-metadata (fetch)
origin  git@github.com:googleapis/gcp-metadata (push)
kelvinjin@spicydays:gcp-metadata$ git remote set-url origin git@github.com:googleapis/gcp-metadata.git
kelvinjin@spicydays:gcp-metadata$ releasetool start
o/ Hey, kelvinjin, let's release some stuff!
> Determining GitHub context.
Origin: googleapis/gcp-metadata, Upstream: googleapis/gcp-metadata
> Comparing origin/master to master.
[...]
```

@ofrobots, were you able to get a chance to see if v0.8 fixed this issue? I tried with the new release (marked 2018.10.25) and it didn't work for me.

I think we should either highlight this in the README or allow `.git` to be omitted, because of the misleading error. I can contribute a PR if needed.

**Comment by busunkim96** [comment]
Yes, it looks like the regex is looking for the `.git`. 

https://github.com/googleapis/releasetool/blob/a8fe19aed1edfca320bfdcee762a46010bc8ef09/releasetool/git.py#L91-L100

**Comment by kjin** [comment]
@ofrobots I think that confirms that this was probably the issue, and that it wasn't fixed yet.
